version: '2'
services:
    debinapp-app:
        image: debinapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://debinapp-postgresql:5432/debinapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    debinapp-postgresql:
        extends:
            file: postgresql.yml
            service: debinapp-postgresql
